### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by moose56** [assetgraph/assetgraph-hashfiles#3]
Been trying to implement hashing functionality for a Svelte.js app for the last 3 days on and off with a vast number of gulp modules.

With assetgraph and assetgraph-hashfiles I implemented it in about 30 minutes.

Thank you.

**Comment by Munter** [comment]
Thank you for the compliment. And let me just say that I find it quite impressive that you figured out an assetgraph setup with assetgraph-hashfiles despite the complete lack of docs on this project 😱

**Comment by moose56** [comment]
The unit tests were good examples of usage
